export { default as Text } from './Text'
export { default as Logo } from './Logo'
export { default as Container } from './Container'
export { default as Footer } from './Footer'
export { default as SourceCode } from './SourceCode'
export { default as Payment } from './Payment'
export { default as Error } from './Error'
export { default as Header } from './Header'
