export { default as login       } from './login'
export { default as register    } from './register'
export { default as getAddress  } from './getAddress'
export { default as getUsername } from './getUsername'
export { default as totalsales  } from './totalsales'
export { default as merchantid  } from './merchantid'
export { default as payments    } from './payments'
