/**
 * GET /login API endpoint
 * @author The Gateway Project Developers <hello@gateway.cash>
 * @file Defines a GET endpoint for /login
 */
import sha256 from 'sha256'
import { mysql, handleError, handleResponse, addAPIKey } from 'utils'

let GET = async (req, res) => {
  // ensure a password was sent
  if (!req.body.password) {
    return handleError(
      'No Password',
      'Provide a password when logging in',
      res
    )
  }

  // verify that either an address or a username was provided
  if (!req.body.address && !req.body.username && !req.body.XPUB) {
    return handleError(
      'Address, Username or XPUB Required',
      'Provide either an address, a username or an XPUB key when logging in',
      res
    )
  }

  // Variable to store the user record
  let user

  // search by address
  if (req.body.address) {
    let result = await mysql.query(
      `SELECT passwordHash, passwordSalt, tableIndex
        FROM users
        WHERE
          payoutAddress = ?
        LIMIT 1`,
      [req.body.address]
    )
    if (result.length !== 1) {
      return handleError(
        'Invalid Login',
        'An incorrect address was given',
        res
      )
    }
    user = result[0]
  }

  // search by username
  if (req.body.username && !user) {
    let result = await mysql.query(
      `SELECT passwordHash, passwordSalt, tableIndex
        FROM users
        WHERE
        username = ?
        LIMIT 1`,
      [req.body.username]
    )
    if (result.length !== 1) {
      return handleError(
        'Invalid Login',
        'An incorrect username was given',
        res
      )
    }
    user = result[0]
  }

  // search by XPUB
  if (req.body.XPUB && !user) {
    let result = await mysql.query(
      `SELECT passwordHash, passwordSalt, tableIndex
        FROM users
        WHERE
        payoutXPUB = ?
        LIMIT 1`,
      [req.body.XPUB]
    )
    if (result.length !== 1) {
      return handleError(
        'Invalid Login',
        'An incorrect XPUB key was given',
        res
      )
    }
    user = result[0]
  }

  // verify a user was found either way
  if (!user) {
    return handleError(
      'Login Error',
      'An unknown error is preventing you from logging in',
      res
    )
  }

  // verify the password
  const passwordHash = sha256(req.body.password + user.passwordSalt)
  if (user.passwordHash === passwordHash) {
    let response = await mysql.query(
      'SELECT APIKey FROM APIKeys WHERE userIndex = ? LIMIT 1',
      [user.tableIndex]
    )
    if (response.length !== 1) {
      /*
        since there were no API keys for this account but the user has just
        verified the credentials we can generate a new API key right now to
        avoid the error
      */
      let newKey = await addAPIKey(
        user.tableIndex,
        'Generated by GET /login',
        res
      )
      return handleResponse({
        APIKey: newKey
      }, res)
    }
    return handleResponse({
      APIKey: response[0].APIKey
    }, res)
  } else {
    return handleError(
      'Invalid Login',
      'An incorrect password was given',
      res
    )
  }
}

export default {
  GET: GET
}
